Iter13
vkupriya/go-metrics pull request #14
Opened 2024-06-11 20:31 UTC by vkupriya

2024-06-14 13:06 UTC, s-shpak commented on cmd/server/...
?

2024-06-14 13:09 UTC, s-shpak commented on internal/server/storage/storage.go
> +			value BIGINT
Это значение может быть `NULL` ?

2024-06-14 13:51 UTC, vkupriya commented on internal/server/handlers/handlers.go
> +	db, err := sql.Open("pgx", mr.config.PostgresDSN)
переделал

2024-06-14 13:56 UTC, vkupriya commented on internal/server/handlers/handlers.go
> +		logger.Sugar().Errorf("failed to get all metrics: %w", err)
поменял на debug

2024-06-14 13:57 UTC, vkupriya commented on internal/server/handlers/handlers.go
> +	_ "github.com/jackc/pgx/v5/stdlib"
убрал

2024-06-14 14:03 UTC, vkupriya commented on internal/server/storage/storage.go
> +			value DOUBLE PRECISION
нет, исправил схему.

2024-06-14 14:29 UTC, vkupriya commented on internal/server/storage/storage.go
> +	createSchema := []string{
добавил создание индекса, хотя я понимаю, что Postgres по умолчанию создаёт для полей UNIQUE

2024-06-14 14:51 UTC, vkupriya commented on internal/server/storage/storage.go
> +			_, err := db.Exec(ctx, "INSERT INTO counter (name, value) VALUES($1, $2)", i.ID, i.Delta)
так и сделал

2024-06-14 14:51 UTC, vkupriya commented on internal/server/storage/storage.go
> +			_, err := tx.Exec(ctx, querySQL, i.ID, i.Value)
да, спасибо за совет. так и сделал. имеет смысл.

2024-06-14 15:00 UTC, vkupriya commented on internal/agent/agent.go
> +				log.Print("failed http post metrics batch, retrying\n")
добавил zap logger в агента, и использую вместо log. также логгирую ошибку.

2024-06-15 09:44 UTC, vkupriya commented on internal/server/storage/storage.go
> +	createSchema := []string{
Сергей, я убрал создание индекса, потому что Postgres для Unique поля 'name' создаёт автоматически. получается дубликат идекса.

2024-06-15 10:23 UTC, vkupriya commented on internal/server/storage/storage.go
> +			_, err := tx.Exec(ctx, querySQL, i.ID, i.Value)
при обработке counter метрик в транзакции - падает авто-тест, так как он посылает дубликат в Batch. Если метрика не существовала до этого в базе, то транзакция падает, потому что вторичный Insert в транзакции для одного и того же counter нарушает уникальность. Обрабатывая каждый counter в Batch отрабатывает отдельно и удовлетворяет авто-тест.

2024-06-19 15:05 UTC, s-shpak commented on internal/server/handlers/handlers.go
> +	// rw.WriteHeader(http.StatusOK)
deadcode

2024-06-19 15:05 UTC, s-shpak commented on internal/server/handlers/handlers.go
> +		logger.Sugar().Errorf("failed to get all metrics: %w", err)
Я имею в виду использование `Field` при логировании: https://pkg.go.dev/go.uber.org/zap#Error

2024-06-19 15:08 UTC, s-shpak requested changes
См. комментарии

2024-06-19 16:31 UTC, vkupriya commented on internal/server/handlers/handlers.go
> +		logger.Sugar().Errorf("failed to get all metrics: %w", err)
logger.Sugar().Debug("failed to get all metrics", zap.Error(err))
уже было заменено, наверное, просматриваешь не обновлённый код.

2024-06-19 16:31 UTC, vkupriya commented on internal/server/handlers/handlers.go
> +	// rw.WriteHeader(http.StatusOK)
убрал deadcode

2024-06-20 16:02 UTC, s-shpak requested changes

2024-06-20 16:02 UTC, s-shpak commented on internal/agent/agent.go
> +				logger.Sugar().Errorf("failed http post metrics batch, retrying: %v\n", err)
Здесь, например, ошибка не обернута в Field. Посмотри и другие места в коде и поправь везде

2024-06-20 19:04 UTC, vkupriya commented on internal/agent/agent.go
> +				logger.Sugar().Errorf("failed http post metrics batch, retrying: %v\n", err)
Добавил Field везде, где пропущено было

2024-06-22 07:40 UTC, merged