first release of iter15
vkupriya/go-metrics pull request #16
Opened 2024-06-26 20:26 UTC by vkupriya

2024-06-27 13:59 UTC, s-shpak requested changes

2024-06-27 13:59 UTC, s-shpak commented on internal/agent/agent.go
>  		select {
Необходимо, чтобы сбор и отправление метрик происходили независимо. Для этого нужно выполнять эти операции в отдельных горутинах

2024-06-27 13:59 UTC, s-shpak commented on internal/agent/agent.go
>  	for k, v := range c.counter {
Я, похоже, просмотрел это, но пакет метрик, может не дойти до сервера, а диспетчер все равно сбросит счетчик. Это необходимо исправить

2024-06-27 13:59 UTC, s-shpak commented on internal/agent/config.go
> +	Mutex          *sync.RWMutex
1. Мьютекс не надо экспортировать - это анти-паттерн
2. Исходя из этого, мьютекс должен быть деталью внутренней реализации структуы и должен относиться к ней, а не к объекту конифигурации

2024-06-27 13:59 UTC, s-shpak commented on internal/agent/agent.go
> +		logger.Sugar().Error(`Cannot get virtual memory`, zap.Error(err))
Почему ошибка логируется здесь, а не отправляется наверх ?

2024-06-27 13:59 UTC, s-shpak commented on internal/agent/agent.go
> +					logger.Sugar().Errorf("failed http post metrics batch, retrying: %v\n", err)
`if retyr == retries`, то мы выйдем из цикла повторов. Тогда это сообщение будет некорректным

2024-06-27 13:59 UTC, s-shpak commented on internal/agent/agent.go
> +				} else {
Постарайся избавиться от вложенности кода

2024-06-27 13:59 UTC, s-shpak commented on internal/agent/agent.go
> +			var (
`retryDelay` и `retries` -- константы

2024-06-27 13:59 UTC, s-shpak commented on internal/agent/agent.go
> +	inputCh := make(chan []Metric)
Кажется, что правильным было бы использовать здесь буферизованный канал

2024-06-27 19:57 UTC, vkupriya commented on internal/agent/agent.go
>  	for k, v := range c.counter {
обнуляю послу успешного отправки.

2024-06-27 19:59 UTC, vkupriya commented on internal/agent/agent.go
>  		select {
разнес код по разным горутинам. получился тройной уровень вложенности. Посмотри - можно ли так делать. Не уверен по-поводу передачи ошибок. Может надо добавить errgroup?

2024-06-27 20:00 UTC, vkupriya commented on internal/agent/config.go
> +	Mutex          *sync.RWMutex
переделал - добавил в структуру Kоллектора

2024-06-27 21:10 UTC, vkupriya commented on internal/agent/agent.go
> +		logger.Sugar().Error(`Cannot get virtual memory`, zap.Error(err))
пробросил.

2024-06-27 21:12 UTC, vkupriya commented on internal/agent/agent.go
> +					logger.Sugar().Errorf("failed http post metrics batch, retrying: %v\n", err)
исправил.

2024-06-27 21:12 UTC, vkupriya commented on internal/agent/agent.go
> +			var (
сделал константами.

2024-06-29 10:16 UTC, vkupriya commented on internal/agent/agent.go
> +				} else {
уменьшил уровень вложенности.

2024-07-01 13:37 UTC, s-shpak requested changes

2024-07-01 13:37 UTC, s-shpak commented on internal/agent/agent.go
> +	g := new(errgroup.Group)
Ты неправильно используешь `errgroup`: если какая-либо ошибка произойдет в одной из горутин, ты не завершишь остальные, т.к. они не будут оповещены о завершении работы. Правильнее будет создать `errgroup` с контекстом и передавать сигнал на заершение через контекст. Посмотри документацию к `errgroup`, чтобы понять как это сделать

2024-07-01 13:37 UTC, s-shpak commented on internal/agent/agent.go
> +	gaugeMutex   sync.RWMutex
Знать о существовании `RWMutex` надо, но пользоваться им -- в общем случае нет (скорее всего твой код будет рабботать медленее при использовании `RWMutex`). Тем более ты используешь эти мьютексы как обычные

2024-07-01 13:37 UTC, s-shpak commented on internal/server/handlers/handlers.go
> +	// r.Use(mh.Hash)
deadcode ?

2024-07-01 13:37 UTC, s-shpak commented on internal/server/middleware/hash.go
> +			http.Error(w, "", http.StatusBadRequest)
Это больше похоже на `internal server error`

2024-07-01 13:37 UTC, s-shpak commented on internal/server/middleware/hash.go
> +			logger.Sugar().Debug("failed to decode hex string", zap.Error(err))
Штатные ошибки не логируются

2024-07-01 13:37 UTC, s-shpak commented on internal/server/middleware/hash.go
> +		mac.Write(b)
Ошибки надо проверять

2024-07-02 07:44 UTC, vkupriya commented on internal/agent/agent.go
> +	gaugeMutex   sync.RWMutex
понял, просмотрел учебные материалы. исправил на обычный.

2024-07-02 07:45 UTC, vkupriya commented on internal/server/handlers/handlers.go
> +	// r.Use(mh.Hash)
удалил закомментированный код.

2024-07-02 07:46 UTC, vkupriya commented on internal/server/middleware/hash.go
> +			http.Error(w, "", http.StatusBadRequest)
да, точно. исправил.

2024-07-02 07:49 UTC, vkupriya commented on internal/server/middleware/hash.go
> +			logger.Sugar().Debug("failed to decode hex string", zap.Error(err))
Даже в дебаге? хорошо - убрал.

2024-07-02 07:57 UTC, vkupriya commented on internal/server/middleware/hash.go
> +		mac.Write(b)
добавил проверку.

2024-07-02 13:38 UTC, s-shpak commented on internal/server/middleware/hash.go
> +			logger.Sugar().Debug("failed to decode hex string", zap.Error(err))
Прошу прощения, не обратил внимания, что это `Debug` уровень. Можно оставить

2024-07-02 13:38 UTC, s-shpak approved these changes

2024-07-03 08:04 UTC, merged