Iter18
vkupriya/go-metrics pull request #27
Opened 2024-08-22 13:01 UTC by vkupriya

2024-08-23 15:19 UTC, s-shpak requested changes
Пока по моим подсчетам общее покрытие кода тестами составляет `20.4%`. Ожидается, что после 18 инкремента покрытие состави `40%`.

Вот как я вычисляю покрытие:

```go
go test -v -coverpkg=./... -coverprofile=profile.cov ./...
go tool cover -func profile.cov
```

Добавь необходимые тесты, пожалуйста. Также добав в `Readme.md` инструкции по вычислению процента покрытия тестами

2024-08-26 18:21 UTC, s-shpak requested changes
Убери, пожалуйста, из анализа сгенерированные файлы: в отчет должен включаться только код, написанный тобой (надо перепроверить, как при этом изменится покрытие: может уменьшиться)

2024-08-26 18:31 UTC, vkupriya commented
> Убери, пожалуйста, из анализа сгенерированные файлы: в отчет должен включаться только код, написанный тобой (надо перепроверить, как при этом изменится покрытие: может уменьшиться)

Ты имеешь ввиду файлы профайлера? удалил и проверил - те же 40.2%

2024-08-26 21:37 UTC, s-shpak requested changes
Нет, я имею в виду моки: их не надо учитывать в финальном отчете.

К сожалению, удобного решения для этой проблемы нет, см. здесь один из возможных подходов: https://stackoverflow.com/questions/50065448/how-to-ignore-generated-files-from-go-test-coverage (третий вариант обычно является самым простым)

2024-08-27 10:28 UTC, s-shpak approved these changes

2024-08-27 12:28 UTC, merged