added compiler set version vars into the metric server main.
vkupriya/go-metrics pull request #29
Opened 2024-09-08 21:23 UTC by vkupriya

2024-09-10 08:14 UTC, s-shpak requested changes
Ты не мог бы перенести код для OSExitChecker в этот PR, пожалуйста ?

2024-09-10 08:14 UTC, s-shpak commented on cmd/server/main.go
> +	fmt.Printf("Build version: %s\n", buildVersion)
Используй логгер вместо `fmt`

2024-09-10 18:23 UTC, vkupriya commented on cmd/server/main.go
> +	fmt.Printf("Build version: %s\n", buildVersion)
done

2024-09-13 10:20 UTC, s-shpak approved these changes

2024-09-17 08:59 UTC, merged