Iter5
vkupriya/go-metrics pull request #5
Opened 2024-05-05 18:36 UTC by vkupriya

2024-05-10 13:35 UTC, s-shpak requested changes
Настрой `golangci-lint` для запуска при помощи Github Actions, см. здесь как https://github.com/s-shpak/praktikum-golangci-lint?tab=readme-ov-file#настройка-github-actions. Поправь проблемы, которые линтер обнаружит

Поправь `metricstest` и `statictest` как описано здесь: https://app.pachca.com/chats/9180496?message=230119157

Обрати внимание, что я пометил не все проблемные места в коде: если одна и та же ошибка встречается несколько раз, то надо поправить ее везде

2024-05-10 13:35 UTC, s-shpak commented on go.mod
> +go 1.21.9
```suggestion
go 1.22.2
```

2024-05-10 13:35 UTC, s-shpak commented on internal/server/flags.go
> +	if envRunAddr := os.Getenv("ADDRESS"); envRunAddr != "" {
Лучше используй `https://pkg.go.dev/os#LookupEnv`

2024-05-10 13:35 UTC, s-shpak commented on cmd/agent/main.go
> +var (
Глобальные переменные не нужны

2024-05-10 13:35 UTC, s-shpak commented on cmd/agent/main.go
Очень много кода: в пакете `main` должен лежать только кода запускающий приложение, не более того. Перенеси в `internal`

2024-05-10 13:35 UTC, s-shpak commented on cmd/agent/main.go
> +				fmt.Println(err)
Используй `log` вместо `fmt`

2024-05-10 13:35 UTC, s-shpak commented on cmd/agent/main.go
> +		mvalue := fmt.Sprintf("%d", v)
Используй `strconv` для перевода чисел в строки

2024-05-10 13:35 UTC, s-shpak commented on cmd/agent/main.go
> +	if envAddr := os.Getenv("ADDRESS"); envAddr != "" {
Лучше используй `https://pkg.go.dev/os#LookupEnv`

2024-05-10 13:35 UTC, s-shpak commented on cmd/agent/main.go
> +			panic(err)
Так нельзя, смотри видео про ошибки: https://app.pachca.com/chats/9180496?message=234290731

2024-05-10 13:35 UTC, s-shpak commented on internal/server/handlers/handlers_test.go
> +				panic(err)
В тестах проверяй ошибки через `assert`

2024-05-10 15:46 UTC, vkupriya commented on cmd/agent/main.go
> +var (
переместил константу в функцию, вместо глобальной

2024-05-10 19:51 UTC, vkupriya commented on cmd/agent/main.go
перенёс в internal

2024-05-11 12:24 UTC, s-shpak requested changes

2024-05-11 12:24 UTC, s-shpak commented on internal/agent/agent.go
> +	metricHost     = flag.String("a", "localhost:8080", "Address and port of the metric server.")
Это глобальные переменные, они не нужны. Используй структуру `config` и функцию, которая эту структуру наполняет и возвращает. В ней должны находиться нужные тебе параметры конфигурации, и ее надо будет прокидывать туда, где эти параметры нужны

2024-05-11 12:24 UTC, s-shpak commented on internal/agent/agent.go
> +				return err
Если не получилось отправить данные на сервер, то лучше просто залогировать ошибку и продолжить выполнение: если сервер стал недоступен по сети, это не повод завершать процесс агента

2024-05-11 12:24 UTC, s-shpak commented on internal/agent/agent.go
> +		mvalue := fmt.Sprintf("%.02f", v)
Для конверсии численных значений надо использовать `strconv`

2024-05-11 12:24 UTC, s-shpak commented on internal/server/flags.go
> +var flagRunAddr string
аналогично

2024-05-11 12:24 UTC, s-shpak commented on internal/server/handlers/handlers.go
> +			if _, err := fmt.Fprintf(rw, "%g", v); err != nil {
1. `strconv`
2. лучше используй `rw.Write()`

2024-05-11 12:24 UTC, s-shpak commented on internal/server/storage/storage.go
> +type Storage interface {
Интерфейсы в Go принято определять там, где они используются

2024-05-11 12:24 UTC, s-shpak commented on templates/index.gohtml
Зачем этот файл, если этот темплейт уже есть в коде ?

2024-05-11 16:56 UTC, vkupriya commented on internal/server/storage/storage.go
> +type Storage interface {
перенёс интерфейс

2024-05-11 16:56 UTC, vkupriya commented on templates/index.gohtml
удалил файл

2024-05-11 17:16 UTC, vkupriya commented on internal/agent/agent.go
> +				return err
теперь легирую и продолжаю. а тогда получается, что ошибку вообще никакую не возвращаю?

2024-05-11 17:17 UTC, vkupriya commented on internal/server/handlers/handlers.go
> +			if _, err := fmt.Fprintf(rw, "%g", v); err != nil {
так линтер рекомендовал.  я поменял на strconv и rw.Write()

2024-05-11 17:20 UTC, vkupriya commented on internal/agent/agent.go
> +		mvalue := fmt.Sprintf("%.02f", v)
изменил на strconv.

2024-05-11 17:23 UTC, vkupriya commented on internal/server/flags.go
> +	if envRunAddr := os.Getenv("ADDRESS"); envRunAddr != "" {
поменял.

2024-05-12 10:19 UTC, vkupriya commented on internal/agent/agent.go
> +	metricHost     = flag.String("a", "localhost:8080", "Address and port of the metric server.")
использовал структуру config для сервера, и агента. В сервере пока не пробрасываю, но сделаю в следующих спринтах, как добавятся другие репозитории/хранилища добавятся другие параметры.

2024-05-12 10:20 UTC, vkupriya commented on internal/server/flags.go
> +var flagRunAddr string
убрал и добавил config.

2024-05-13 21:24 UTC, s-shpak requested changes

2024-05-13 21:24 UTC, s-shpak commented on internal/server/storage/storage.go
> +type Storage interface {
Этот интерфейс надо удалить из кода

2024-05-13 22:11 UTC, vkupriya commented on internal/server/storage/storage.go
> +type Storage interface {
а он у меня удалён. я его перенёс в handlers.go

2024-05-13 22:54 UTC, s-shpak approved these changes

2024-05-13 23:36 UTC, merged