Iter9
vkupriya/go-metrics pull request #9
Opened 2024-05-27 20:59 UTC by vkupriya

2024-05-29 17:38 UTC, s-shpak requested changes

2024-05-29 17:38 UTC, s-shpak commented on internal/server/middleware/logger.go
> +		r.done = true
Можно сделать проще: выстави статус 200 по умолчанию

2024-05-29 17:38 UTC, s-shpak commented on internal/server/handlers/handlers.go
> +		logger.Sugar().Debug("unsupported metric type", zap.String("type", req.MType))
Штатные ошибки (которые приводят к статусу < 500) не надо логировать

2024-05-29 17:38 UTC, s-shpak commented on internal/server/middleware/gzip.go
> +			gr, err := gzip.NewReader(r.Body)
См. документацию к этому компоненту: оригинальный ридер надо закрыть

2024-05-29 17:38 UTC, s-shpak commented on internal/server/middleware/gzip.go
> +				http.Error(w, "", http.StatusInternalServerError)
`InternalServerError` надо логировать

2024-05-29 17:38 UTC, s-shpak commented on internal/server/storage/storage.go
> +func NewMemStorage(c *models.Config) (*MemStorage, error) {
Мне не нравится текущая имплементация: MemStorage и FileStorage лучше сделать независимыми

Хотелось бы, чтобы:

Из конструктора хранилища возвращался объект общего интерфейса
Существовало две имплементации харинилища - in-memory и файловая
Файловое хранилище было оберткой надо in-memory: то есть встаривало бы in-memory при помощи композиции
В итоге сервису должно быть безразлично, сохраняем ли мы данные в файл или нет.

Если что-то непонятно из этого - уточни в пачке

2024-05-29 17:38 UTC, s-shpak commented on internal/server/storage/storage.go
> +var (
Глобальные переменные не нужны

2024-05-29 17:38 UTC, s-shpak commented on internal/server/handlers/handlers_test.go
> +	"log"
В объекте `t` есть инструмент логирования, так что этот импорт не нужен

2024-05-29 17:38 UTC, s-shpak commented on internal/server/middleware/gzip.go
> +	"log"
Используй `zap` везде, дефолтный логер больше не нужен

2024-05-29 20:22 UTC, vkupriya commented on internal/server/storage/storage.go
> +func NewMemStorage(c *models.Config) (*MemStorage, error) {
переделал.

2024-05-29 20:34 UTC, vkupriya commented on internal/server/middleware/gzip.go
> +			gr, err := gzip.NewReader(r.Body)
а у меня вроде был Close: 

defer func() {
				if err := gr.Close(); err != nil {
					logger.Sugar().Error(err)
					http.Error(w, "", http.StatusInternalServerError)
				}
			}()

2024-05-29 20:34 UTC, vkupriya commented on internal/server/handlers/handlers.go
> +		logger.Sugar().Debug("unsupported metric type", zap.String("type", req.MType))
убрал

2024-05-29 20:46 UTC, vkupriya commented on internal/server/middleware/logger.go
> +		r.done = true
у меня не все правильно отрабатывалось при статусе 200 по умолчанию, поэтому усложнил. Поменял опять на 200 по умолчанию. Вроде пока корректно и успешные и нет отрабатываются.

2024-05-29 20:47 UTC, vkupriya commented on internal/server/middleware/gzip.go
> +				http.Error(w, "", http.StatusInternalServerError)
добавил лог.

2024-05-29 21:00 UTC, vkupriya commented on internal/server/storage/storage.go
> +var (
убрал

2024-05-29 21:00 UTC, vkupriya commented on internal/server/handlers/handlers_test.go
> +	"log"
переделал

2024-05-30 06:15 UTC, s-shpak requested changes

2024-05-30 06:15 UTC, s-shpak commented on internal/server/middleware/gzip.go
> +func (l *MiddlewareLogger) GzipHandle(h http.Handler) http.Handler {
Почему это метод `MiddlewareLogger` ?

2024-05-30 12:01 UTC, vkupriya commented on internal/server/middleware/gzip.go
> +func (l *MiddlewareLogger) GzipHandle(h http.Handler) http.Handler {
cоздал для GzipHandle свою структуру.

2024-05-30 18:12 UTC, s-shpak approved these changes

2024-05-30 18:57 UTC, merged